>- # Scikit-Learn Library:
- ## Importing Libraries:

In [1]:
import pandas as pd
import numpy as np

In [2]:
DF=pd.read_csv('extended_car_sales.csv')

In [3]:
DF

,Make,Colour,Odometer (KM),Doors,Price
0,Honda,White,35431.0,4.0,15323.0
1,BMW,Blue,192714.0,5.0,19943.0
2,Honda,White,84714.0,4.0,28343.0
3,Toyota,White,154365.0,4.0,13434.0
4,Nissan,Blue,181577.0,3.0,14043.0
...,...,...,...,...,...
995,Toyota,Black,35820.0,4.0,32042.0
996,NaN,White,155144.0,3.0,5716.0
997,Nissan,Blue,66604.0,4.0,31570.0
998,Honda,White,215883.0,4.0,4001.0


In [4]:
DF.head(20)

,Make,Colour,Odometer (KM),Doors,Price
0,Honda,White,35431.0,4.0,15323.0
1,BMW,Blue,192714.0,5.0,19943.0
2,Honda,White,84714.0,4.0,28343.0
3,Toyota,White,154365.0,4.0,13434.0
4,Nissan,Blue,181577.0,3.0,14043.0
5,Honda,Red,42652.0,4.0,23883.0
6,Toyota,Blue,163453.0,4.0,8473.0
7,Honda,White,NaN,4.0,20306.0
8,NaN,White,130538.0,4.0,9374.0
9,Honda,Blue,51029.0,4.0,26683.0


In [5]:
DF.tail(20)

,Make,Colour,Odometer (KM),Doors,Price
980,Toyota,Blue,230314.0,4.0,6720.0
981,Toyota,White,129454.0,4.0,6446.0
982,Honda,White,238172.0,4.0,13273.0
983,Toyota,Red,NaN,4.0,14671.0
984,Nissan,Blue,157235.0,4.0,4196.0
985,NaN,Blue,216250.0,4.0,9691.0
986,Honda,White,71934.0,4.0,26882.0
987,Honda,White,215235.0,4.0,3825.0
988,Nissan,Black,248736.0,4.0,8358.0
989,Toyota,Red,41735.0,4.0,13928.0


In [6]:
DF.dtypes

Make              object
Colour            object
Odometer (KM)    float64
Doors            float64
Price            float64
dtype: object

In [7]:
Columns=DF.columns
Columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [8]:
DF.isnull()

,Make,Colour,Odometer (KM),Doors,Price
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
995,False,False,False,False,False
996,True,False,False,False,False
997,False,False,False,False,False
998,False,False,False,False,False


In [9]:
DF.isnull().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [10]:
DF.isnull().sum().sum()

249

In [11]:
DF.dropna(subset='Price',axis=0,inplace=True)
DF['Price']

0      15323.0
1      19943.0
2      28343.0
3      13434.0
4      14043.0
        ...   
995    32042.0
996     5716.0
997    31570.0
998     4001.0
999    12732.0
Name: Price, Length: 950, dtype: float64

- Getting the data ready for model training
- Preprocessing
- Handling Missing Values(Imputation)

In [12]:
X=DF.drop('Price',axis=1)
Y=DF['Price']

In [13]:
X

,Make,Colour,Odometer (KM),Doors
0,Honda,White,35431.0,4.0
1,BMW,Blue,192714.0,5.0
2,Honda,White,84714.0,4.0
3,Toyota,White,154365.0,4.0
4,Nissan,Blue,181577.0,3.0
...,...,...,...,...
995,Toyota,Black,35820.0,4.0
996,NaN,White,155144.0,3.0
997,Nissan,Blue,66604.0,4.0
998,Honda,White,215883.0,4.0


In [14]:
Y

0      15323.0
1      19943.0
2      28343.0
3      13434.0
4      14043.0
        ...   
995    32042.0
996     5716.0
997    31570.0
998     4001.0
999    12732.0
Name: Price, Length: 950, dtype: float64

In [15]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
Num_Cols=["Odometer (KM)","Doors"]
Cat_Cols=DF.select_dtypes(include='object').columns
Cat_Imputer=SimpleImputer(strategy='constant',fill_value='missing')
Num_Imputer=SimpleImputer(strategy='mean')
Imputer=ColumnTransformer(
    [("Category Imputing",Cat_Imputer,Cat_Cols),
    ("Numerical Imputing",Num_Imputer,Num_Cols)])
Filled_X=Imputer.fit_transform(X)

In [16]:
Cat_Cols

Index(['Make', 'Colour'], dtype='object')

In [17]:
Filled_X

array([['Honda', 'White', 35431.0, 4.0],
       ['BMW', 'Blue', 192714.0, 5.0],
       ['Honda', 'White', 84714.0, 4.0],
       ...,
       ['Nissan', 'Blue', 66604.0, 4.0],
       ['Honda', 'White', 215883.0, 4.0],
       ['Toyota', 'Blue', 248360.0, 4.0]], dtype=object)

In [18]:
Car_Filled_DF=pd.DataFrame(Filled_X,columns=['Make','Colour','Odometer (KM)','Doors'])
Car_Filled_DF

,Make,Colour,Odometer (KM),Doors
0,Honda,White,35431.0,4.0
1,BMW,Blue,192714.0,5.0
2,Honda,White,84714.0,4.0
3,Toyota,White,154365.0,4.0
4,Nissan,Blue,181577.0,3.0
...,...,...,...,...
945,Toyota,Black,35820.0,4.0
946,missing,White,155144.0,3.0
947,Nissan,Blue,66604.0,4.0
948,Honda,White,215883.0,4.0


In [60]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
Cat_Cols2=['Make','Colour']
One_Hot=OneHotEncoder()
Encoder=ColumnTransformer(
    [("One_Hot_Encoding",One_Hot,Cat_Cols2)],remainder="passthrough")
X_Transformed=Encoder.fit_transform(Car_Filled_DF)

In [61]:
X_Transformed

array([[0.0, 1.0, 0.0, ..., 0.0, 35431.0, 4.0],
       [1.0, 0.0, 0.0, ..., 0.0, 192714.0, 5.0],
       [0.0, 1.0, 0.0, ..., 0.0, 84714.0, 4.0],
       ...,
       [0.0, 0.0, 1.0, ..., 0.0, 66604.0, 4.0],
       [0.0, 1.0, 0.0, ..., 0.0, 215883.0, 4.0],
       [0.0, 0.0, 0.0, ..., 0.0, 248360.0, 4.0]], dtype=object)

In [62]:
X_Transformed.shape , X_Transformed.ndim

((950, 13), 2)

In [63]:
print(type(X_Transformed))

<class 'numpy.ndarray'>


In [64]:
X_DF=pd.DataFrame( X_Transformed , 
                   columns=Encoder.get_feature_names_out())
X_DF

,One_Hot_Encoding__Make_BMW,One_Hot_Encoding__Make_Honda,One_Hot_Encoding__Make_Nissan,One_Hot_Encoding__Make_Toyota,One_Hot_Encoding__Make_missing,One_Hot_Encoding__Colour_Black,One_Hot_Encoding__Colour_Blue,One_Hot_Encoding__Colour_Green,One_Hot_Encoding__Colour_Red,One_Hot_Encoding__Colour_White,One_Hot_Encoding__Colour_missing,remainder__Odometer (KM),remainder__Doors
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35431.0,4.0
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,192714.0,5.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,84714.0,4.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,154365.0,4.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,181577.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,35820.0,4.0
946,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,155144.0,3.0
947,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,66604.0,4.0
948,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,215883.0,4.0


In [65]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
RFR=RandomForestRegressor()
X_Train,X_Test,Y_Train,Y_Test = train_test_split(X_Transformed,Y,test_size=0.2,random_state=42)
RFR.fit(X_Train,Y_Train)

RandomForestRegressor()

In [66]:
RFR.fit(X_Train,Y_Train);

In [76]:
Y_Pred=RFR.predict(X_Test)
Y_Pred

array([17629.06      , 21029.97      , 12358.41      ,  9311.01      ,
       11630.77      , 11432.7       , 14931.63      ,  9535.92      ,
       17087.36      , 15869.74967731,  8315.28      , 17316.18      ,
        8273.08      ,  9307.37      , 12335.31      , 18498.97      ,
       16160.98      ,  6710.41      , 11075.8       , 15223.73      ,
       11752.03      , 17995.89607143, 19918.65      , 27681.9       ,
        8978.396     , 20869.96      , 12569.69      ,  8383.62      ,
       20033.24      , 18628.91      , 12289.4       , 15377.59      ,
       11088.25      , 11720.18634524, 28793.47      , 16308.54      ,
       12303.26      , 12652.44      , 22124.9       , 10147.48      ,
       14955.55      , 19744.49      , 24698.85      , 15900.39      ,
       14498.525     , 11565.57      , 14639.92      ,  8046.26      ,
       15180.36      , 14478.04      , 11112.79      , 19520.77      ,
       16972.14      ,  6305.88      , 11771.55      ,  9196.03      ,
      

In [77]:
Y_Test

203    10547.0
979    17940.0
729    12950.0
838     5905.0
919     9826.0
        ...   
625    10377.0
33      9780.0
31      6866.0
746    16705.0
305    18375.0
Name: Price, Length: 190, dtype: float64

In [78]:
RFR.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [90]:
from sklearn.metrics import r2_score
R2=r2_score(Y_Pred,Y_Test)
R2

-0.3175188917566656

In [91]:
from sklearn.model_selection import cross_val_score
Cross_Validations=cross_val_score(RFR,X_Transformed,Y,cv=10)

In [82]:
Cross_Validations

array([ 0.11863841,  0.12069772,  0.27541305,  0.25133124,  0.13229384,
        0.44168866,  0.18703843,  0.16191334, -0.00610816,  0.49605904])

In [110]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
Parameter_Grid1 = {
    'n_estimators':[100,200],
    'max_depth': [3,5,10]
}
Parameter_Grid2 = {
     'n_estimators':[100,200,300,500],
    'max_depth': [5,10,20],
    'min_samples_split': [2,10,15]
}

In [111]:
Grid_Search=GridSearchCV(
    RandomForestRegressor(random_state=42),
    Parameter_Grid1,
    n_jobs=1,
    cv=10,
    scoring='r2',
    verbose=2
)

In [112]:
Random_Search=RandomizedSearchCV(
    RandomForestRegressor(random_state=42),
    Parameter_Grid2,
    n_iter=20,
    n_jobs=1,
    random_state=42,
    scoring='r2',
    verbose=2
)

In [113]:
Grid_Search.fit(X_Train,Y_Train)

Fitting 10 folds for each of 6 candidates, totalling 60 fits
[CV] END ......................max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ......................max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ......................max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ......................max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ......................max_depth=3, n_estimators=100; total time=   0.0s
[CV] END ......................max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ......................max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ......................max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ......................max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ......................max_depth=3, n_estimators=100; total time=   0.1s
[CV] END ......................max_depth=3, n_estimators=200; total time=   0.2s
[CV] END ......................max_depth=3, n_es

GridSearchCV(cv=10, estimator=RandomForestRegressor(random_state=42), n_jobs=1,
             param_grid={'max_depth': [3, 5, 10], 'n_estimators': [100, 200]},
             scoring='r2', verbose=2)

In [114]:
print(Grid_Search.best_estimator_)

RandomForestRegressor(max_depth=3, n_estimators=200, random_state=42)


In [115]:
Grid_Search.best_params_

{'max_depth': 3, 'n_estimators': 200}

In [132]:
RFR2=RandomForestRegressor(max_depth=3,n_estimators=200,random_state=42)
RFR2.fit(X_Train,Y_Train)

RandomForestRegressor(max_depth=3, n_estimators=200, random_state=42)

In [135]:
Y_Predict2=RFR2.predict(X_Test)
R2_2=r2_score(Y_Test,Y_Predict2)
R2_2

0.3364502587607672

In [136]:
Random_Search.fit(X_Train,Y_Train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV] END max_depth=20, min_samples_split=15, n_estimators=500; total time=   1.0s
[CV] END max_depth=20, min_samples_split=15, n_estimators=500; total time=   1.0s
[CV] END max_depth=20, min_samples_split=15, n_estimators=500; total time=   1.0s
[CV] END max_depth=20, min_samples_split=15, n_estimators=500; total time=   0.9s
[CV] END max_depth=20, min_samples_split=15, n_estimators=500; total time=   1.0s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=20, min_samples_split=2, n_estimators=300; total time=   0.8s
[CV] END max_depth=20, min_samples_split=2

RandomizedSearchCV(estimator=RandomForestRegressor(random_state=42), n_iter=20,
                   n_jobs=1,
                   param_distributions={'max_depth': [5, 10, 20],
                                        'min_samples_split': [2, 10, 15],
                                        'n_estimators': [100, 200, 300, 500]},
                   random_state=42, scoring='r2', verbose=2)

In [140]:
print(Random_Search.best_estimator_);

RandomForestRegressor(max_depth=5, min_samples_split=10, n_estimators=200,
                      random_state=42)


In [141]:
Random_Search.best_params_

{'n_estimators': 200, 'min_samples_split': 10, 'max_depth': 5}

In [148]:
RFR3=RandomForestRegressor(random_state=42,n_estimators=200,min_samples_split=10,max_depth=5)
RFR3.fit(X_Train,Y_Train)
Y_Pred3=RFR3.predict(X_Test)
R2_3=r2_score(Y_Test,Y_Pred3)
R2_3

0.33409830416346653

In [150]:
r2_score(Y_Test,Y_Pred3)

0.33409830416346653

In [152]:
np.random.seed(50)
for i in range(100,200,10):
    RFR4=RandomForestRegressor(n_estimators=i).fit(X_Train,Y_Train)
    Y_Pred4=RFR4.predict(X_Test)
    print(f'At n_estimator = {i} R^2 Of Model = {r2_score(Y_Test,Y_Pred4)}')

At n_estimator = 100 R^2 Of Model = 0.20152639005835282
At n_estimator = 110 R^2 Of Model = 0.1985207487816606
At n_estimator = 120 R^2 Of Model = 0.21171411064779044
At n_estimator = 130 R^2 Of Model = 0.21926450949860687
At n_estimator = 140 R^2 Of Model = 0.21418744810445378
At n_estimator = 150 R^2 Of Model = 0.22584249498400333
At n_estimator = 160 R^2 Of Model = 0.20813698169233363
At n_estimator = 170 R^2 Of Model = 0.21165004978124924
At n_estimator = 180 R^2 Of Model = 0.21754436483093964
At n_estimator = 190 R^2 Of Model = 0.20566475742738455


In [154]:
import pickle
pickle.dump(RFR,open("Poor_Car_Sale_Model.pkl","wb"))

In [155]:
Model=pickle.load(open("Poor_Car_Sale_Model.pkl","rb"))

In [156]:
Model.predict(X_Test)


array([17629.06      , 21029.97      , 12358.41      ,  9311.01      ,
       11630.77      , 11432.7       , 14931.63      ,  9535.92      ,
       17087.36      , 15869.74967731,  8315.28      , 17316.18      ,
        8273.08      ,  9307.37      , 12335.31      , 18498.97      ,
       16160.98      ,  6710.41      , 11075.8       , 15223.73      ,
       11752.03      , 17995.89607143, 19918.65      , 27681.9       ,
        8978.396     , 20869.96      , 12569.69      ,  8383.62      ,
       20033.24      , 18628.91      , 12289.4       , 15377.59      ,
       11088.25      , 11720.18634524, 28793.47      , 16308.54      ,
       12303.26      , 12652.44      , 22124.9       , 10147.48      ,
       14955.55      , 19744.49      , 24698.85      , 15900.39      ,
       14498.525     , 11565.57      , 14639.92      ,  8046.26      ,
       15180.36      , 14478.04      , 11112.79      , 19520.77      ,
       16972.14      ,  6305.88      , 11771.55      ,  9196.03      ,
      